name: BlockchainAssets
favicon: null
layout_spectrum: 0.83936
typography_spectrum: 0.49894
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d57bb'
    - '#fb8424'
    - '#b93a14'
    - '#3d0503'
    - '#fcc42d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
